-- P2 EXERCICE 6 : Edition des clients tries par region et profession

-- Tri : 1) CODE_REGION, 2) CODE_PROF, 3) NUM_COMPTE
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       R.CODE_REGION, R.NOM_REGION,
       P.CODE_PROF, P.LIB_PROF,
       C.SOLDE, C.POS
FROM CLIENT C
INNER JOIN REGION R ON C.CODE_REGION = R.CODE_REGION
INNER JOIN PROFESSI P ON C.CODE_PROF = P.CODE_PROF
ORDER BY C.CODE_REGION, C.CODE_PROF, C.NUM_COMPTE;
