-- P2 EXERCICE 1 : Extraction des clients par profession

-- Clients COMPTABLE
SELECT * FROM CLIENT WHERE CODE_PROF = '15';

-- Clients FONCTIONNAIRE
SELECT * FROM CLIENT WHERE CODE_PROF = '25';

-- Clients MEDECIN
SELECT * FROM CLIENT WHERE CODE_PROF = '05';

-- DROP VIEW V_CLIENT_COMPTABLE;
-- DROP VIEW V_CLIENT_FONCTION;
-- DROP VIEW V_CLIENT_MEDECIN;

-- Vues avec jointure (libelle profession)
CREATE VIEW V_CLIENT_COMPTABLE AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       P.CODE_PROF, P.LIB_PROF
FROM CLIENT C
INNER JOIN PROFESSI P ON C.CODE_PROF = P.CODE_PROF
WHERE P.LIB_PROF = 'COMPTABLE';

CREATE VIEW V_CLIENT_FONCTION AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       P.CODE_PROF, P.LIB_PROF
FROM CLIENT C
INNER JOIN PROFESSI P ON C.CODE_PROF = P.CODE_PROF
WHERE P.LIB_PROF = 'FONCTIONNAIRE';

CREATE VIEW V_CLIENT_MEDECIN AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       P.CODE_PROF, P.LIB_PROF
FROM CLIENT C
INNER JOIN PROFESSI P ON C.CODE_PROF = P.CODE_PROF
WHERE P.LIB_PROF = 'MEDECIN';

-- Verification des vues
SELECT * FROM V_CLIENT_COMPTABLE;
SELECT * FROM V_CLIENT_FONCTION;
SELECT * FROM V_CLIENT_MEDECIN;
