-- P2 EXERCICE 3 : Repartition des clients par region

-- Clients region PARIS (01)
SELECT * FROM CLIENT WHERE CODE_REGION = '01';

-- Clients region MARSEILLE (02)
SELECT * FROM CLIENT WHERE CODE_REGION = '02';

-- Clients region LYON (03)
SELECT * FROM CLIENT WHERE CODE_REGION = '03';

-- Clients region LILLE (04)
SELECT * FROM CLIENT WHERE CODE_REGION = '04';

-- DROP VIEW V_CLIENT_PARIS;
-- DROP VIEW V_CLIENT_MARSEILLE;
-- DROP VIEW V_CLIENT_LYON;
-- DROP VIEW V_CLIENT_LILLE;

-- Vues avec jointure (nom region)
CREATE VIEW V_CLIENT_PARIS AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       R.CODE_REGION, R.NOM_REGION, C.SOLDE, C.POS
FROM CLIENT C
INNER JOIN REGION R ON C.CODE_REGION = R.CODE_REGION
WHERE R.NOM_REGION = 'PARIS';

CREATE VIEW V_CLIENT_MARSEILLE AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       R.CODE_REGION, R.NOM_REGION, C.SOLDE, C.POS
FROM CLIENT C
INNER JOIN REGION R ON C.CODE_REGION = R.CODE_REGION
WHERE R.NOM_REGION = 'MARSEILLE';

CREATE VIEW V_CLIENT_LYON AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       R.CODE_REGION, R.NOM_REGION, C.SOLDE, C.POS
FROM CLIENT C
INNER JOIN REGION R ON C.CODE_REGION = R.CODE_REGION
WHERE R.NOM_REGION = 'LYON';

CREATE VIEW V_CLIENT_LILLE AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       R.CODE_REGION, R.NOM_REGION, C.SOLDE, C.POS
FROM CLIENT C
INNER JOIN REGION R ON C.CODE_REGION = R.CODE_REGION
WHERE R.NOM_REGION = 'LILLE';

-- Verification des vues
SELECT * FROM V_CLIENT_PARIS;
SELECT * FROM V_CLIENT_MARSEILLE;
SELECT * FROM V_CLIENT_LYON;
SELECT * FROM V_CLIENT_LILLE;
