-- P2 EXERCICE 7 : Fusion COMPTABLES + FONCTIONNAIRES

-- Fusion avec UNION
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       P.CODE_PROF, P.LIB_PROF,
       C.SOLDE, C.POS
FROM CLIENT C
INNER JOIN PROFESSI P ON C.CODE_PROF = P.CODE_PROF
WHERE P.LIB_PROF = 'COMPTABLE'
UNION
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       P.CODE_PROF, P.LIB_PROF,
       C.SOLDE, C.POS
FROM CLIENT C
INNER JOIN PROFESSI P ON C.CODE_PROF = P.CODE_PROF
WHERE P.LIB_PROF = 'FONCTIONNAIRE';
