-- P2 EXERCICE 5 : Index secondaire sur CODE_PROF

-- DROP INDEX IDX_CLIENT_PROF;
-- COMMIT;
CREATE INDEX IDX_CLIENT_PROF ON CLIENT(CODE_PROF);

-- Verification
SELECT * FROM CLIENT WHERE CODE_PROF = '15';
