-- P2 EXERCICE 8 : Vue CLIENT reduit

-- DROP VIEW V_CLIENT_REDUIT;

CREATE VIEW V_CLIENT_REDUIT AS
SELECT NUM_COMPTE,
       CODE_REGION,
       CODE_NATCPT,
       NOM_CLIENT,
       PREN_CLIENT,
       CODE_PROF,
       SIT_FAM,
       SOLDE,
       POS
FROM CLIENT;

-- Verification
SELECT * FROM V_CLIENT_REDUIT;
