-- P2 EXERCICE 2 : Repartition selon la position du compte (DB/CR)

-- Clients debiteurs (DB)
SELECT * FROM CLIENT WHERE POS = 'DB';

-- Clients crediteurs (CR)
SELECT * FROM CLIENT WHERE POS = 'CR';

-- DROP VIEW V_CLIENT_DEBITEUR;
-- DROP VIEW V_CLIENT_CREDITEUR;

-- Vues pour reutilisation COBOL-DB2
CREATE VIEW V_CLIENT_DEBITEUR AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       C.SOLDE, C.POS
FROM CLIENT C
WHERE C.POS = 'DB';

CREATE VIEW V_CLIENT_CREDITEUR AS
SELECT C.NUM_COMPTE, C.NOM_CLIENT, C.PREN_CLIENT,
       C.SOLDE, C.POS
FROM CLIENT C
WHERE C.POS = 'CR';

-- Verification des vues
SELECT * FROM V_CLIENT_DEBITEUR;
SELECT * FROM V_CLIENT_CREDITEUR;
