-- P2 EXERCICE 4 : Index secondaire sur CODE_REGION

-- DROP INDEX IDX_CLIENT_REGION;
-- COMMIT;
CREATE INDEX IDX_CLIENT_REGION ON CLIENT(CODE_REGION);

-- Verification
SELECT * FROM CLIENT WHERE CODE_REGION = '01';
