-- EXERCICE 1 : Creation des tables
-- Note: POS remplace POSITION (mot reserve COBOL)

DROP TABLE REGION;
CREATE TABLE REGION (
    CODE_REGION CHAR(2) NOT NULL PRIMARY KEY,
    NOM_REGION  VARCHAR(15)
);

DROP TABLE NATCOMPT;
CREATE TABLE NATCOMPT (
    CODE_NATCPT CHAR(2) NOT NULL PRIMARY KEY,
    LIB_NATCPT  VARCHAR(30)
);

DROP TABLE PROFESSI;
CREATE TABLE PROFESSI (
    CODE_PROF CHAR(2) NOT NULL PRIMARY KEY,
    LIB_PROF  VARCHAR(20)
);

DROP TABLE CLIENT;
CREATE TABLE CLIENT (
    NUM_COMPTE   CHAR(3) NOT NULL PRIMARY KEY,
    CODE_REGION  CHAR(2) REFERENCES REGION(CODE_REGION),
    CODE_NATCPT  CHAR(2) REFERENCES NATCOMPT(CODE_NATCPT),
    NOM_CLIENT   VARCHAR(10),
    PREN_CLIENT  VARCHAR(10),
    DATE_NAIS    DATE,
    SEXE         CHAR(1),
    CODE_PROF    CHAR(2) REFERENCES PROFESSI(CODE_PROF),
    SIT_FAM      CHAR(1),
    ADRESSE      VARCHAR(20),
    SOLDE        DECIMAL(10,2),
    POS          CHAR(2),
    CHECK(POS IN ('DB','CR'))
);
