-- P2 EXERCICE 9 : Analyse multi-criteres par region

SELECT R.CODE_REGION,
       R.NOM_REGION,
       COUNT(*) AS NB_TOTAL,
       SUM(CASE WHEN C.POS = 'DB' THEN 1 ELSE 0 END) AS NB_DEBITEURS,
       SUM(CASE WHEN C.POS = 'CR' THEN 1 ELSE 0 END) AS NB_CREDITEURS,
       SUM(CASE WHEN C.POS = 'DB' THEN C.SOLDE ELSE 0 END) AS SOLDE_DEBITEUR,
       SUM(CASE WHEN C.POS = 'CR' THEN C.SOLDE ELSE 0 END) AS SOLDE_CREDITEUR
FROM CLIENT C
INNER JOIN REGION R ON C.CODE_REGION = R.CODE_REGION
GROUP BY R.CODE_REGION, R.NOM_REGION
ORDER BY R.CODE_REGION;
