-- P2 EXERCICE 9 : Analyse multi-criteres par region

SELECT
  CODE_REGION,
  COUNT(*)
     AS "NB CLIENTS",
  SUM(CASE WHEN POS = 'DB' THEN 1 ELSE 0 END)
     AS "NB DEBITEURS",
  SUM(CASE WHEN POS = 'CR' THEN 1 ELSE 0 END)
     AS "NB CREDITEURS",
  SUM(CASE WHEN POS = 'DB' THEN SOLDE ELSE 0 END)
     AS "SOLDE TOTAL DEBITEURS",
  SUM(CASE WHEN POS = 'CR' THEN SOLDE ELSE 0 END)
     AS "SOLDE TOTAL CREDITEURS"
FROM CLIENT
GROUP BY CODE_REGION;
